name: Company
version: '${version}'
depend: [AutoPickup]
main: com.whiteroad.Company
api-version: '1.20'
description: '회사 플러그인'
author: "['RoadRome','baekji04']"
commands:
  company:
    description: 회사 관리 명령어
    usage: /company <하위명령어> [인수...]
    aliases: [c,회사]
    permission: company.command.default
    permission-message: 해당 명령어를 사용할 권한이 없습니다.
    subcommands:
      창설:
        description: 회사를 창설합니다
        usage: /company 창설 <회사이름>
        permission: company.command.create
      폐업:
        description: 회사를 폐업합니다
        usage: /company 폐업 <회사이름>
        permission: company.command.close
      리스트:
        description: 회사 목록을 표시합니다
        usage: /company 리스트 [페이지]
        permission: company.command.list
      정보:
        description: 회사 정보를 표시합니다
        usage: /company 정보 <회사이름>
        permission: company.command.info
      관리:
        description: 회사 정보를 수정합니다
        usage: /company 관리 <회사이름> <속성> <값>
        permission: company.command.manage
      주식시장:
        description: 주식 시장을 활성화 또는 비활성화합니다
        usage: /company 주식시장 <on/off>
        permission: company.command.stocktoggle
      주식요일제:
        description: 주식 시장 요일을 설정합니다
        usage: /company 주식요일제 <이진값>
        permission: company.command.stockmarket
      테스트:
        description: 주식 기능을 테스트합니다
        usage: /company 테스트 <인수1> <인수2>
        permission: company.command.test
      일일업무:
        description: 일일 업무를 엽니다
        usage: /company 일일업무
        permission: company.command.dailytasks

permissions:
  company.command.default:
    description: 기본 회사 명령어 액세스
    default: op
  company.command.create:
    description: 회사 생성 권한
    default: op
  company.command.close:
    description: 회사 폐쇄 권한
    default: op
  company.command.list:
    description: 회사 목록 조회 권한
    default: op
  company.command.info:
    description: 회사 정보 조회 권한
    default: op
  company.command.manage:
    description: 회사 정보 관리 권한
    default: op
  company.command.stockmarket:
    description: 주식 시장 관리 권한
    default: op
  company.command.stocktoggle:
    description: 주식 시장 관리 권한
    default: op
  company.command.test:
    description: 주식 기능 테스트 권한
    default: op
  company.command.dailytasks:
    description: 일일 업무 열기 권한
    default: op

aliases:
  cp: company
  del: delete
  list: li
  info: if